
version: '3.8'
services:
  db:
    image: mysql
    container_name: pokemonShop          
    restart: always
    environment:
      MYSQL_DATABASE: pokemon_shop                  
      MYSQL_ROOT_PASSWORD: ${password}
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_db_data:/var/lib/mysql  

volumes:
  mysql_db_data:
